on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 14 * * *"  

jobs:
  daily-task:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "This is a scheduled task running at $(date)"
